apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-${ENVIRONMENT:-dev}
  namespace: ${GKE_NAMESPACE:-default}
  labels:
    app: ${SERVICE_NAME}
    environment: ${ENVIRONMENT:-dev}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: ${SERVICE_NAME}
    environment: ${ENVIRONMENT:-dev}

