apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenwebapi123
  namespace: default
  labels:
    app: zenwebapi123
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zenwebapi123
  template:
    metadata:
      labels:
        app: zenwebapi123
    spec:
      containers:
      - name: zenwebapi123
        image: asia-east1-a-docker.pkg.dev/dev-zephyr-352206/zenwebapi123/zenwebapi123:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openweather-api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: zenwebapi123-service
  namespace: default
spec:
  selector:
    app: zenwebapi123
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
